# Generated by Django 5.2.1 on 2025-05-22 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitudcotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='servicio_interesado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicio'),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='descripcion_evento',
            field=models.TextField(help_text='Describe brevemente el servicio o evento que te interesa (si no seleccionaste uno específico arriba)'),
        ),
    ]
