# Generated by Django 5.2.1 on 2025-05-28 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mensajecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notificaciones_admin', models.EmailField(help_text='Correo donde se recibirán las notificaciones de nuevas solicitudes de cotización, mensajes de contacto, etc.', max_length=254, verbose_name='Email para Notificaciones del Administrador')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
