# Generated by Django 5.2.1 on 2025-05-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracionsitio_solicitudcotizacion_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='ticket_id',
        ),
    ]
