# Generated by Django 5.2.1 on 2025-06-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_solicitudcotizacion_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(help_text="Escribe la pregunta exacta o palabras clave principales que un usuario podría preguntar (ej. 'horario atencion pago').", max_length=255, unique=True)),
                ('respuesta', models.TextField(help_text='La respuesta que el chatbot debe dar.')),
            ],
            options={
                'verbose_name': 'Pregunta/Respuesta del Chatbot',
                'verbose_name_plural': 'Preguntas y Respuestas del Chatbot',
            },
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='chatbot_fallback_response',
            field=models.TextField(default='No he entendido tu pregunta. ¿Podrías reformularla? Si necesitas ayuda personalizada, contáctanos.', help_text='Lo que el chatbot dirá si no encuentra una respuesta. Puedes incluir enlaces o correos.', verbose_name='Respuesta por Defecto del Chatbot'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='email_notificaciones_admin',
            field=models.EmailField(help_text='Correo donde se recibirán las notificaciones.', max_length=254, verbose_name='Email para Notificaciones del Administrador'),
        ),
    ]
