# Generated by Django 5.2.1 on 2025-06-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chatbotqa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotqa',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='chatbot_fallback_response',
        ),
        migrations.AddField(
            model_name='chatbotqa',
            name='keywords',
            field=models.TextField(default='', help_text='Escribe palabras clave que activarán esta respuesta, separadas por comas. Ej: horario, atencion, abierto', verbose_name='Palabras Clave (separadas por comas)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='email_notificaciones_admin',
            field=models.EmailField(help_text='Correo donde se recibirán las notificaciones de nuevas solicitudes de cotización, mensajes de contacto, etc.', max_length=254, verbose_name='Email para Notificaciones del Administrador'),
        ),
    ]
