# Generated by Django 5.2.1 on 2025-06-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_chatbotqa_pregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para que este servicio aparezca en la sección de destacados de la página de inicio.', verbose_name='Servicio Destacado'),
        ),
    ]
