# Generated by Django 5.2.1 on 2025-06-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicio_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Slide')),
                ('subtitle', models.TextField(blank=True, max_length=500, verbose_name='Subtítulo del Slide (opcional)')),
                ('background_image', models.ImageField(upload_to='hero_slides/', verbose_name='Imagen de Fondo')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Enlace del Botón (opcional)')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Texto del Botón (opcional)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Slide de Inicio',
                'verbose_name_plural': 'Slides de Inicio',
                'ordering': ['order'],
            },
        ),
    ]
