# Generated by Django 5.2.1 on 2025-06-19 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_heroslide_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(blank=True, help_text='Precio base del servicio.', null=True, verbose_name='Precio Base (Opcional)'),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_oferta', models.PositiveIntegerField(help_text='El precio especial con el descuento aplicado.', verbose_name='Precio de Oferta')),
                ('descripcion_oferta', models.CharField(blank=True, max_length=255, null=True, verbose_name="Descripción de la oferta (ej: 'Solo por este mes!')")),
                ('activa', models.BooleanField(default=True, help_text='Desmarca esta casilla para ocultar la oferta sin borrarla.', verbose_name='¿Oferta activa?')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to='core.servicio', verbose_name='Servicio asociado')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
