# Generated by Django 5.2.1 on 2025-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_servicio_precio_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='telefono_cliente',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
