# Generated by Django 5.2.1 on 2025-06-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_solicitudcotizacion_telefono_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Proyecto')),
                ('fecha_realizacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Realización')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para que se muestre en la página de inicio.')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (0 primero).')),
            ],
            options={
                'verbose_name': 'Proyecto Realizado',
                'verbose_name_plural': 'Proyectos Realizados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SeccionSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Transformamos Tu Visión en un Evento Inolvidable', max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_principal', models.ImageField(upload_to='sobre_nosotros/', verbose_name='Imagen Principal de la Sección')),
            ],
            options={
                'verbose_name': 'Sección Sobre Nosotros',
                'verbose_name_plural': 'Sección Sobre Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.TextField(verbose_name='Cita o Comentario')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor del testimonio')),
                ('descripcion_autor', models.CharField(blank=True, max_length=150, verbose_name="Descripción del autor (ej: 'Matrimonio, Enero 2025')")),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/', verbose_name='Imagen del Proyecto')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo (accesibilidad)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de Proyecto',
                'verbose_name_plural': 'Imágenes de Proyectos',
            },
        ),
        migrations.CreateModel(
            name='PuntoClaveSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto del Punto Clave')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_clave', to='core.seccionsobrenosotros')),
            ],
            options={
                'verbose_name': 'Punto Clave',
                'verbose_name_plural': 'Puntos Clave',
                'ordering': ['orden'],
            },
        ),
    ]
