# Generated by Django 5.2.1 on 2025-06-19 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_proyecto_seccionsobrenosotros_testimonio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionsobrenosotros',
            name='imagen_principal',
        ),
        migrations.CreateModel(
            name='ImagenSobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='sobre_nosotros_galeria/', verbose_name='Imagen de la Galería')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.seccionsobrenosotros')),
            ],
            options={
                'verbose_name': 'Imagen de Sobre Nosotros',
                'verbose_name_plural': 'Imágenes de Sobre Nosotros',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenTestimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='testimonios/', verbose_name='Imagen del Testimonio')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('testimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.testimonio')),
            ],
            options={
                'verbose_name': 'Imagen de Testimonio',
                'verbose_name_plural': 'Imágenes de Testimonios',
            },
        ),
    ]
