# Generated by Django 5.2.1 on 2025-06-26 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_seccionsobrenosotros_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Solo llenar si este ítem es un Pack.', null=True, verbose_name='Duración en Horas (para Packs)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='has_tiered_pricing',
            field=models.BooleanField(default=False, help_text='Marcar si este servicio tiene múltiples precios (ej. por horas).', verbose_name='¿Usa Precios por Niveles?'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='max_guests',
            field=models.PositiveIntegerField(blank=True, help_text='Solo llenar si este ítem es un Pack.', null=True, verbose_name='Máximo de Invitados (para Packs)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('PACK', 'Pack Prediseñado'), ('INDEPENDIENTE', 'Producto o Servicio Independiente'), ('ADICIONAL_PACK', 'Adicional exclusivo para Pack')], default='INDEPENDIENTE', help_text='Clasifica el ítem como un Pack o un servicio individual.', max_length=20, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para que aparezca en la sección de destacados.', verbose_name='Servicio Destacado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio base del ítem. Si usa precios por niveles, dejar en 0.', max_digits=10, verbose_name='Precio Base'),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Ej: '2 horas', '2 Robot en zancos'", max_length=255)),
                ('price', models.DecimalField(decimal_places=0, help_text='Precio para este nivel, sin decimales.', max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='core.servicio')),
            ],
            options={
                'verbose_name': 'Nivel de Precio',
                'verbose_name_plural': 'Niveles de Precio',
            },
        ),
    ]
