# Generated by Django 5.2.1 on 2025-06-26 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_servicio_duration_hours_servicio_has_tiered_pricing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(help_text='Sube una imagen o un video corto (MP4).', upload_to='servicios_media/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video')], default='IMAGE', max_length=10, verbose_name='Tipo de Medio')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la galería.')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_gallery', to='core.servicio')),
            ],
            options={
                'verbose_name': 'Medio de Servicio',
                'verbose_name_plural': 'Galería de Medios del Servicio',
                'ordering': ['orden'],
            },
        ),
    ]
