# Generated by Django 5.2.1 on 2025-06-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='permite_cantidad',
            field=models.BooleanField(default=False, help_text='Marcar si este servicio es por unidades (ej: horas extra, sillas adicionales).', verbose_name='¿Permite seleccionar cantidad?'),
        ),
    ]
