# Generated by Django 5.2.1 on 2025-06-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_servicio_permite_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='servicios_compatibles',
            field=models.ManyToManyField(blank=True, help_text='Si este es un servicio ADITIVO, selecciona a qué servicios principales se puede añadir.', to='core.servicio', verbose_name='Servicios Principales Compatibles'),
        ),
    ]
