# Generated by Django 5.2.1 on 2025-06-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_servicio_servicios_compatibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
    ]
