# Generated by Django 5.2.1 on 2025-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_servicio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='atendida',
        ),
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='servicio_interesado',
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='cotizacion_detallada_json',
            field=models.TextField(blank=True, help_text='Datos JSON serializados de los ítems del carrito.', null=True, verbose_name='Detalles de Cotización (JSON)'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COTIZADO', 'Cotizado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='descripcion_evento',
            field=models.TextField(blank=True, help_text='Descripción adicional del evento proporcionada por el cliente.', null=True),
        ),
    ]
