# Generated by Django 5.2.1 on 2025-06-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_solicitudcotizacion_atendida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='servicio',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='El valor numérico de la duración (ej: 30, 2, 5).', null=True, verbose_name='Duración (valor)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('MINUTOS', 'Minutos'), ('HORAS', 'Horas')], default='HORAS', help_text='La unidad para el valor de duración (Horas o Minutos).', max_length=10, null=True, verbose_name='Unidad de Duración'),
        ),
    ]
