# Generated by Django 5.2.1 on 2025-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_servicio_duration_hours_servicio_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='max_cantidad',
            field=models.PositiveIntegerField(blank=True, help_text='Si permite cantidad, establece un límite. Déjalo vacío para no tener límite.', null=True, verbose_name='Cantidad Máxima (Opcional)'),
        ),
    ]
